# Generated by Django 2.0.5 on 2018-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('upassword', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('BODYBUILDING', 'bodybuilding'), ('WEIGHTLOSE', 'weightlose'), ('LEANBODY', 'leanbody'), ('SHREDED', 'shreded'), ('BULKBODY', 'bulkbody')], max_length=40)),
                ('diet_type', models.CharField(blank=True, choices=[('NONVEG', 'nonveg'), ('VEG', 'veg')], max_length=40)),
            ],
        ),
    ]
