# Generated by Django 2.0.5 on 2018-10-31 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('BODYBUILDING', 'bodybuilding'), ('WEIGHTLOSE', 'weightlose'), ('LEANBODY', 'leanbody'), ('SHREDED', 'shreded'), ('BULKBODY', 'bulkbody')], max_length=40)),
                ('diet_type', models.CharField(blank=True, choices=[('NONVEG', 'nonveg'), ('VEG', 'veg')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
